TestNAVBAR/Controllers/SMSController.cs
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace TestNAVBAR.Controllers
{
	  public class SMSController : Controller
	  {
			string T24Response = "";
			string selectedchurchbranch = "";
			string _successfailview = "";
			string selectedchurch = "";
			string sql = "";
			string Duser = "";
			Dictionary<string, string> where = new Dictionary<string, string>();
			System.Data.SqlClient.SqlDataReader rd;
			BusinessLogic.Users userdata = new BusinessLogic.Users();
			BusinessLogic.DataConnections Blogic = new BusinessLogic.DataConnections();
			Logic.TCPLogic tcplogic = new Logic.TCPLogic();
			Logic.DMLogic bizzlogic = new Logic.DMLogic();
			//
			// GET: /SMS/

			public ActionResult Index()
			{
				  return View();
			}

			[NoDirectAccessAttribute]
			[AcceptVerbs(HttpVerbs.Get)]
			public ActionResult CallLogs()
			{

				  return View();
			}
			[NoDirectAccessAttribute]
			[AcceptVerbs(HttpVerbs.Get)]
			public ActionResult Lu()
			{

				  return View();
			}
			[NoDirectAccessAttribute]
			[AcceptVerbs(HttpVerbs.Get)]
			public ActionResult othersms()
			{

				  return View();
			}
		
			[AcceptVerbs(HttpVerbs.Post)]
			public ActionResult CallLogs(FormCollection collection)
			{
				  string _viewtoDisplay = "";
				  string _action = collection[2];
				  string _action_w = collection[3];
				  string _SQLSelectionCriteria = "";
				  List<string> errors = new List<string>();
				  ViewData["ModelErrors"] = errors;

				  if (_action_w.ToString() == "Search") //phone
				  {

						string _mpesano = collection["mpesano"];


						if (collection["mpesano"].ToString().Length == 0)
						{
							  errors.Add("You must Indicate the MPESA No.");
						}

						if (collection["mpesano"].ToString().Length > 0)
						{
							  _SQLSelectionCriteria = "WHERE customerphone='" + _mpesano + "'";
						}

				  }
				  else if (_action.ToString() == "Load")//dates
				  {
						string _startdate = collection["bp.startdate"];
						string _enddate = collection["bp.enddate"];
						//string _mpesano = collection["mpesano"];

						string ftodate = "";


						string ftenddate = "";

						if (collection["bp.startdate"].ToString().Length == 0 || collection["bp.startdate"].ToString().Contains("mm/"))
						{
							  errors.Add("You must Indicate a valid start Date.");
						}

						if (collection["bp.enddate"].ToString().Length == 0 || collection["bp.enddate"].ToString().Contains("mm/"))
						{
							  errors.Add("You must Indicate a valid  End Date.");
						}
						//Build SQL Selection criteria to pass as a single session value
						if (collection["bp.startdate"].ToString().Length > 0 && !collection["bp.startdate"].ToString().Contains("mm/"))
						{
							  ftodate = Convert.ToDateTime(_startdate).ToString("yyyy-MM-dd");
							  _startdate = ftodate;
							  _SQLSelectionCriteria = " WHERE CallDate>='" + _startdate + "'";
						}

						if (collection["bp.enddate"].ToString().Length > 0 && !collection["bp.startdate"].ToString().Contains("mm/"))
						{
							  ftenddate = Convert.ToDateTime(_enddate).ToString("yyyy-MM-dd");
							  _enddate = ftenddate;
							  _SQLSelectionCriteria = _SQLSelectionCriteria + " " + " AND CallDate<='" + _enddate + "'";
						}
				  }
				  if (_SQLSelectionCriteria.Length == 0)
				  {
						errors.Add("The selection Criteria cannot be empty!!");
				  }

				  if (errors.Count > 0)
				  {
						_viewtoDisplay = "CallLogs";
				  }
				  else
				  {
						_viewtoDisplay = "CallLogDates";

						System.Web.HttpContext.Current.Session["SQLSelectionCriteria"] = _SQLSelectionCriteria.ToString();

				  }


				  return View(_viewtoDisplay);
			}
			[AcceptVerbs(HttpVerbs.Post)]
			public ActionResult Lu(FormCollection collection)
			{
				  string _viewtoDisplay = "Lu";
				  string _action = collection[4];
				  if (_action == "Load")
				  {
						//-------------------------
						_viewtoDisplay = "LuDates";
						List<string> errors = new List<string>();
						ViewData["ModelErrors"] = errors;
						string _startdate = collection["bp.startdate"];
						string _enddate = collection["bp.enddate"];
						string _mpesano = collection["customerphone"];

						string _SQLSelectionCriteria = "";

						if (collection["bp.startdate"].ToString().Length > 0)
						{
							  _SQLSelectionCriteria = " WHERE CallDate>='" + _startdate + "'";
						}

						if (collection["bp.enddate"].ToString().Length > 0)
						{
							  _SQLSelectionCriteria = _SQLSelectionCriteria + " " + " AND CallDate<='" + _enddate + "'";
						}

						if (collection["customerphone"].ToString().Length > 0)
						{
							  _SQLSelectionCriteria = _SQLSelectionCriteria + " " + "  AND customerphone='" + _mpesano + "'";
						}

						System.Web.HttpContext.Current.Session["SQLSelectionCriteria"] = _SQLSelectionCriteria.ToString();
						// ----------------------------


				  }
				  return View(_viewtoDisplay);
			}
			[NoDirectAccessAttribute]
			[AcceptVerbs(HttpVerbs.Get)]
			public ActionResult SMSLogs()
			{
				  return View();
			}
			[AcceptVerbs(HttpVerbs.Post)]
			public ActionResult SMSLogs(FormCollection collection)
			{
				  string _viewtoDisplay = "";
				  string _action = collection[2];
				  string _action_w = collection[3];
				  string _SQLSelectionCriteria = "";
				  List<string> errors = new List<string>();
				  ViewData["ModelErrors"] = errors;

				  if (_action_w.ToString() == "Search") //phone
				  {

						string _mpesano = collection["mpesano"];


						if (collection["mpesano"].ToString().Length == 0)
						{
							  errors.Add("You must Indicate the MPESA No.");
						}

						if (collection["mpesano"].ToString().Length > 0)
						{
							  _SQLSelectionCriteria = "WHERE phonenumber='" + _mpesano + "'";
						}

				  }
				  else if (_action.ToString() == "Load")//dates
				  {
						string _startdate = collection["bp.startdate"];
						string _enddate = collection["bp.enddate"];
						//string _mpesano = collection["mpesano"];

						string ftodate = "";


						string ftenddate = "";

						if (collection["bp.startdate"].ToString().Length == 0 || collection["bp.startdate"].ToString().Contains("mm/"))
						{
							  errors.Add("You must Indicate a valid start Date.");
						}

						if (collection["bp.enddate"].ToString().Length == 0 || collection["bp.enddate"].ToString().Contains("mm/"))
						{
							  errors.Add("You must Indicate a valid  End Date.");
						}
						//Build SQL Selection criteria to pass as a single session value
						if (collection["bp.startdate"].ToString().Length > 0 && !collection["bp.startdate"].ToString().Contains("mm/"))
						{
							  ftodate = Convert.ToDateTime(_startdate).ToString("yyyy-MM-dd");
							  _startdate = ftodate;
							  _SQLSelectionCriteria = " WHERE datecreated>='" + _startdate + "'";
						}

						if (collection["bp.enddate"].ToString().Length > 0 && !collection["bp.startdate"].ToString().Contains("mm/"))
						{
							  ftenddate = Convert.ToDateTime(_enddate).ToString("yyyy-MM-dd");
							  _enddate = ftenddate;
							  _SQLSelectionCriteria = _SQLSelectionCriteria + " " + " AND datecreated<='" + _enddate + "'";
						}
				  }
				  if (_SQLSelectionCriteria.Length == 0)
				  {
						errors.Add("The selection Criteria cannot be empty!!");
				  }

				  if (errors.Count > 0)
				  {
						_viewtoDisplay = "SMSLogs";
				  }
				  else
				  {
						_viewtoDisplay = "MpesaDates";

						System.Web.HttpContext.Current.Session["SQLSelectionCriteria"] = _SQLSelectionCriteria.ToString();

				  }


				  return View(_viewtoDisplay);
			}
		
			[AcceptVerbs(HttpVerbs.Post)]
			public ActionResult BList(FormCollection collection)
			{
				  string _viewtoDisplay = "BList";
				  string _action = collection[4];
				  if (_action == "Load")
				  {
						//-------------------------
						_viewtoDisplay = "BListDates";
						List<string> errors = new List<string>();
						ViewData["ModelErrors"] = errors;
						string _startdate = collection["bp.startdate"];
						string _enddate = collection["bp.enddate"];
						string _mpesano = collection["mpesano"];

						string _SQLSelectionCriteria = "";

						if (collection["bp.startdate"].ToString().Length == 0)
						{
							  errors.Add("You must Indicate the start Date.");
						}

						if (collection["bp.enddate"].ToString().Length == 0)
						{
							  errors.Add("You must Indicate the End Date.");
						}
						if (collection["bp.startdate"].ToString().Length > 0)
						{
							  _SQLSelectionCriteria = " WHERE datelogged>='" + _startdate + "'";
						}

						if (collection["bp.enddate"].ToString().Length > 0)
						{
							  _SQLSelectionCriteria = _SQLSelectionCriteria + " " + " AND datelogged<='" + _enddate + "'";
						}

						if (collection["mpesano"].ToString().Length > 0)
						{
							  _SQLSelectionCriteria = _SQLSelectionCriteria + " " + "  AND phonenumber='" + _mpesano + "'";
						}

						System.Web.HttpContext.Current.Session["SQLSelectionCriteria"] = _SQLSelectionCriteria.ToString();

				  }
				  return View(_viewtoDisplay);
			}

			[AcceptVerbs(HttpVerbs.Get)]
			public ActionResult PrintCallLogs(string id)
			{
				  return View();
			}

			[AcceptVerbs(HttpVerbs.Get)]
			public ActionResult PrintSMSLogs(string id)
			{
				  return View();
			}
			[NoDirectAccessAttribute]
			[AcceptVerbs(HttpVerbs.Get)]
			public ActionResult LoanUsers()
			{
				  return View();
			}
			[NoDirectAccessAttribute]
			[AcceptVerbs(HttpVerbs.Get)]
			public ActionResult LoanUserss()
			{
				  return View();
			}
			[NoDirectAccessAttribute]
			[AcceptVerbs(HttpVerbs.Get)]
			public ActionResult LoanUsersList()
			{
				  return View();
			}
			[NoDirectAccessAttribute]
			[AcceptVerbs(HttpVerbs.Get)]
			public ActionResult LoanUsersWList()
			{
				  return View();
			}
			[NoDirectAccessAttribute]
			[AcceptVerbs(HttpVerbs.Get)]

TestNAVBAR/Views/SMS/LoanUsersBList.cshtml
@{
    Layout = "~/Views/Shared/_LayoutD.cshtml";
}
@model TestNAVBAR.Models.ListDatabaseElements

<h4 class="content-wrapper" style="padding-bottom:10px;margin-left:300px;">Loan Users Data</h4>

<script language="javascript" type="text/javascript">

var t;
window.onload=resetTimer;
document.onkeypress=resetTimer;

function logout()
{
	//alert(" You are now logged out.")
	location.href = 'http://34.238.242.42:3370/Tsalvon/Account/Login'


        }
        function resetTimer()
        {
        clearTimeout(t);
         t = setTimeout(logout, 7200000) //logs out in 1hr min
}

</script>

<script type="text/javascript" src="https://code.jquery.com/jquery-1.12.3.js"></script>
<script type="text/javascript" src="https://cdn.datatables.net/1.10.12/js/jquery.dataTables.min.js"></script>

<script language="javascript" type="text/javascript">

$(document).ready(function() {
    $('#MyTable').DataTable( {"aLengthMenu": [[100, 400, , 800, 1000, -1], [100, 400, 800, 1000, "ALL"]],
        "iDisplayLength": 800,
        initComplete: function () {
            this.api().columns().every( function () {
                var column = this;
                var select = $('<select><option value=""></option></select>')
                    .appendTo( $(column.footer()).empty() )
                    .on( 'change', function () {
                        var val = $.fn.dataTable.util.escapeRegex(
                            $(this).val()
                        );
                //to select and search from grid
                        column
                            .search( val ? '^'+val+'$' : '', true, false )
                            .draw();
                    } );

                column.data().unique().sort().each( function ( d, j ) {
                    select.append( '<option value="'+d+'">'+d+'</option>' )
                } );
            } );
        }
    } );
} );
</script>



@using (Html.BeginForm())
{
    FormCollection collection = (FormCollection)ViewData["collection"];
    TestNAVBAR.Models.ListDatabaseElements bp = new TestNAVBAR.Models.ListDatabaseElements();
    List<Dictionary<string, object>> listusers = bp.LoanUsersBList;
    List<string> errors = (List<string>)ViewData["ModelErrors"];
    ViewData["ModelErrors"] = null;
    if (errors != null)
    {
        for (int i = 0; i < errors.Count; ++i)
        {
            var item = errors[i];
            <div class="message-info content-wrapper " style="color:red;border:none;">
                <ul>
                    <li>@Html.Encode(item)</li>
                </ul>

            </div>
        }
    }
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    if (listusers != null && listusers.Count > 0)
    {
        <div style="width:100%;margin-left:20px;margin-right:20px;padding-top: 10px;padding-left: 5px;padding-right: 5px;padding-bottom: 10px;border: 1px solid;clear: both;margin: 0 auto;max-width: 1320px;">
            <table>
                <thead>
                    <tr>
                        <th>
                            BlackList
                        </th>
                        <th>
                            First Name
                        </th>
                        <th>
                            Middle Name
                        </th>
                        <th>
                            Last Name
                        </th>
                        <th>
                            Email Address
                        </th>
                        <th>
                            Phone Number
                        </th>
                        <th>
                            Date of Birth
                        </th>
                        <th>
                            Gender
                        </th>
                    </tr>
                </thead>
                <tbody>
                    @for (int i = 0; i < listusers.Count; ++i)
                    {
                        var item = listusers[i];
                        <tr>
                            <td>@Html.ActionLink("BlackList", "ViewLoanUsersBList", new { id = @item["id"] })</td>
                            <td>@item["firstname"]</td>
                            <td>@item["middlename"]</td>
                            <td>@item["lastname"]</td>
                            <td>@item["emailaddress"]</td>
                            <td>@item["phonenumber"]</td>
                            <td>@item["dateofbirth"]</td>
                            <td>@item["gender"]</td>
                        </tr>
                    }
                </tbody>
            </table>
            <fieldset class="small">
                <input type="submit" value="Authorise" />
            </fieldset>
        </div>
    }

    <br></br>
    <br></br>
    <br></br>
    <br></br>
    <br></br>
    <br></br>

}

TestNAVBAR/Views/SMS/Lu.cshtml
@{
    Layout = "~/Views/Shared/_LayoutD.cshtml";
}
@model TestNAVBAR.Models.ListDatabaseElements

<h4 class="content-wrapper" style="padding-bottom:10px;margin-left:300px;">Call Logs Data</h4>

<script language="javascript" type="text/javascript">

var t;
window.onload=resetTimer;
document.onkeypress=resetTimer;

function logout()
{
	//alert(" You are now logged out.")
	location.href = 'http://34.238.242.42:3370/Tsalvon/Account/Login'


        }
        function resetTimer()
        {
        clearTimeout(t);
         t = setTimeout(logout, 7200000) //logs out in 1hr min
}

</script>

<script type="text/javascript" src="https://code.jquery.com/jquery-1.12.3.js"></script>
<script type="text/javascript" src="https://cdn.datatables.net/1.10.12/js/jquery.dataTables.min.js"></script>

<script language="javascript" type="text/javascript">

$(document).ready(function() {
    $('#MyTable').DataTable({
        "aLengthMenu": [[100, 400, , 800, 1000, -1], [100, 400, 800, 1000, "ALL"]],
        "iDisplayLength": 800,
        initComplete: function () {
            this.api().columns().every( function () {
                var column = this;
                var select = $('<select><option value=""></option></select>')
                    .appendTo( $(column.footer()).empty() )
                    .on( 'change', function () {
                        var val = $.fn.dataTable.util.escapeRegex(
                            $(this).val()
                        );
                //to select and search from grid
                        column
                            .search( val ? '^'+val+'$' : '', true, false )
                            .draw();
                    } );

                column.data().unique().sort().each( function ( d, j ) {
                    select.append( '<option value="'+d+'">'+d+'</option>' )
                } );
            } );
        }
    } );
} );
</script>

@using (Html.BeginForm())
{
    FormCollection collection = (FormCollection)ViewData["collection"];
    TestNAVBAR.Models.ListDatabaseElements bp = new TestNAVBAR.Models.ListDatabaseElements();
    List<Dictionary<string, object>> listusers = bp.CallLogs;
    List<string> errors = (List<string>)ViewData["ModelErrors"];
    ViewData["ModelErrors"] = null;
    if (errors != null)
    {
        for (int i = 0; i < errors.Count; ++i)
        {
            var item = errors[i];
            <div class="message-info content-wrapper " style="color:red;border:none;">
                <ul>
                    <li>@Html.Encode(item)</li>
                </ul>

            </div>
        }
    }
    //Html.RenderAction("CallLogDates","SMS");
    Html.RenderAction("LoanUsersDates", "SMS");
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    @*if (listusers != null && listusers.Count > 0)
    {
        <div style="width:100%;margin-left:20px;margin-right:20px;padding-top: 10px;padding-left: 5px;padding-right: 5px;padding-bottom: 10px;border: 1px solid;clear: both;margin: 0 auto;max-width: 1320px;">
            <table id="MyTable" class="display" cellspacing="0" width="100%">
                <thead>
                    <tr>
                        <th>
                            Phone No:
                        </th>
                        <th>
                            Call Date
                        </th>
                        <th>
                            Duration
                        </th>
                        <th>
                            Call Type
                        </th>
                        <th>
                            Customer Phone
                        </th>
                        <th>
                            Date Logged
                        </th>
                    </tr>
                </thead>
                <tbody>
                    @for (int i = 0; i < listusers.Count; ++i)
                    {
                        var item = listusers[i];
                        <tr>
                            <td>@item["phonenumber"]</td>
                            <td>@item["calldate"]</td>
                            <td>@item["duration"]</td>
                            <td>@item["calltype"]</td>
                            <td>@item["customerphone"]</td>
                            <td>@item["datelogged"]</td>
                        </tr>
                    }
                </tbody>
            </table>*@

            @*<fieldset class="small">
                  <input type="submit" value="Authorise" />
                </fieldset>*@
        @*</div>*@
    }

    <br></br>
    <br></br>
    <br></br>
    <br></br>
    <br></br>
    <br></br>

}

TestNAVBAR/Views/SMS/othersms.cshtml
@{
    Layout = "~/Views/Shared/_LayoutD.cshtml";
}
@model TestNAVBAR.Models.ListDatabaseElements

@*<h4 class="content-wrapper" style="padding-bottom:10px;margin-left:250px;">Loan Users <br />NB: Phone numbers must start with 2547xxxxxxx</h4>*@

<script language="javascript" type="text/javascript">

var t;
window.onload=resetTimer;
document.onkeypress=resetTimer;

function logout()
{
	//alert(" You are now logged out.")
	location.href = 'http://34.238.242.42:3370/Tsalvon/Account/Login'
            }
        function resetTimer()
        {
        clearTimeout(t);
         t = setTimeout(logout, 7200000) //logs out in 1hr min
}

</script>

<script type="text/javascript" src="https://code.jquery.com/jquery-1.12.3.js"></script>
<script type="text/javascript" src="https://cdn.datatables.net/1.10.12/js/jquery.dataTables.min.js"></script>

<script language="javascript" type="text/javascript">

$(document).ready(function() {
    $('#MyTable').DataTable({
        "aLengthMenu": [[100, 400, , 800, 1000, -1], [100, 400, 800, 1000, "ALL"]],
        "iDisplayLength": 800,
        initComplete: function () {
            this.api().columns().every( function () {
                var column = this;
                var select = $('<select><option value=""></option></select>')
                    .appendTo( $(column.footer()).empty() )
                    .on( 'change', function () {
                        var val = $.fn.dataTable.util.escapeRegex(
                            $(this).val()
                        );
                //to select and search from grid
                        column
                            .search( val ? '^'+val+'$' : '', true, false )
                            .draw();
                    } );
                    column.data().unique().sort().each( function ( d, j ) {
                    select.append( '<option value="'+d+'">'+d+'</option>' )
                } );
            } );
        }
    } );
} );
</script>

<script language="javascript" type="text/javascript">
    $(document).ready(function() {
        var a="";
        if(navigator.userAgent.indexOf("Firefox") != -1 )
        {
            //alert('Firefox');
            a='firefox';
        }

        $(function () {
            var b=a;
            if (a == 'firefox') {
                $('.date-picker').datepicker({ dateFormat: 'dd-mm-yy' });
            }else{
                $('#Start Date').datepicker({ dateFormat: 'dd-mm-yy' });
            }
            ///This will make every element with the class "date-picker" into a DatePicker element

        });

    });
</script>


@using (Html.BeginForm())
{
    FormCollection collection = (FormCollection)ViewData["collection"];
    TestNAVBAR.Models.ListDatabaseElements bp = new TestNAVBAR.Models.ListDatabaseElements();
    List<Dictionary<string, object>> listusers = bp.SMSLogsportal;
    List<string> errors = (List<string>)ViewData["ModelErrors"];
    ViewData["ModelErrors"] = null;
    if (errors != null)
    {
        for (int i = 0; i < errors.Count; ++i)
        {
            var item = errors[i];
            <div class="message-info content-wrapper " style="color:red;border:none;max-width: 1000px;">
                <ul>
                    <li>@Html.Encode(item)</li>
                </ul>

            </div>
        }
    }
    //Html.RenderAction("LoanUsersDates", "SMS");
    <div class="container" style="width:100%;margin-left:300px;border: 1px solid;max-width: 500px;">
        <h5>Search using dates</h5>
        <fieldset>
            <legend>Search Criteria</legend>
            <p>
                <label>start Date</label>
                @Html.TextBoxFor(model => bp.startdate, "", new { @class = "form-control date-picker datepicker date-picker .date-picker", placeholder = "Enter start date here", type = "date" })
                <label>
                </label>
                <label>End Date</label>
                @Html.TextBoxFor(model => bp.enddate, new { @class = "form-control  date-picker datepicker date-picker .date-picker", placeholder = "Enter End date here", type = "date" })
            </p><p>
                
                <input name="masiku" type="submit" value="Load" id="AuthoriseButton" onclick="javascript:return Postsubmit();" />
            </p>
        </fieldset>
    </div>
    <div class="container" style="width:100%;margin-left:300px;border: 1px solid;max-width: 500px;">
        <h5>Search using PhoneNumber</h5>
        <fieldset>
            <p>
                <label>Phone No</label>
                @Html.TextBox("mpesano", @ViewData["mpesano"])
            </p>
            <p>
             
                <legend>Actions</legend>

                <input name="simu" type="submit" value="Search" id="printButton" onclick="javascript:return Postsubmit();" />
            </p>
        </fieldset>
    </div>
    if (listusers != null && listusers.Count > 0)
    {
        <div style="width:100%;margin-left:20px;margin-right:20px;padding-top: 10px;padding-left: 5px;padding-right: 5px;padding-bottom: 10px;border: 1px solid;clear: both;margin: 0 auto;max-width: 1320px;">
            <table id="MyTable" class="display" cellspacing="0" width="100%">
                <thead>
                    <tr>

                        <th>
                            Sender
                        </th>
                        <th>
                            Message
                        </th>

                        <th>
                            Recepient
                        </th>

                        <th>
                            sent time
                        </th>
                    </tr>
                </thead>
                <tbody>
                    @for (int i = 0; i < listusers.Count; ++i)
                    {
                        var item = listusers[i];
                        <tr>

                            <td>@item["sender"]</td>
                            <td>@item["message"]</td>
                            <td>@item["customerphone"]</td>
                            <td>@item["senttime"]</td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    }

    <br></br>
    <br></br>
    <br></br>
    <br></br>
    <br></br>
    <br></br>

}
@*@model TestNAVBAR.Models.ListDatabaseElements

<h4 class="content-wrapper" style="padding-bottom:10px">Portal SMS Logs Data</h4>

<script language="javascript" type="text/javascript">

var t;
window.onload=resetTimer;
document.onkeypress=resetTimer;

function logout()
{
	//alert(" You are now logged out.")
	location.href = 'http://34.238.242.42:3370/Tsalvon/Account/Login'


        }
        function resetTimer()
        {
        clearTimeout(t);
         t = setTimeout(logout, 7200000) //logs out in 1hr min
}

</script>

<script type="text/javascript" src="https://code.jquery.com/jquery-1.12.3.js"></script>
<script type="text/javascript" src="https://cdn.datatables.net/1.10.12/js/jquery.dataTables.min.js"></script>

<script language="javascript" type="text/javascript">

$(document).ready(function() {
    $('#MyTable').DataTable({
        "aLengthMenu": [[100, 400, , 800, 1000, -1], [100, 400, 800, 1000, "ALL"]],
        "iDisplayLength": 800,
        initComplete: function () {
            this.api().columns().every( function () {
                var column = this;
                var select = $('<select><option value=""></option></select>')
                    .appendTo( $(column.footer()).empty() )
                    .on( 'change', function () {
                        var val = $.fn.dataTable.util.escapeRegex(
                            $(this).val()
                        );
                //to select and search from grid
                        column
                            .search( val ? '^'+val+'$' : '', true, false )
                            .draw();
                    } );

                column.data().unique().sort().each( function ( d, j ) {
                    select.append( '<option value="'+d+'">'+d+'</option>' )
                } );
            } );
        }
    } );
} );
</script>

@using (Html.BeginForm())
{
    FormCollection collection = (FormCollection)ViewData["collection"];
    TestNAVBAR.Models.ListDatabaseElements bp = new TestNAVBAR.Models.ListDatabaseElements();
    List<Dictionary<string, object>> listusers = bp.SMSLogsportal;
    List<string> errors = (List<string>)ViewData["ModelErrors"];
    ViewData["ModelErrors"] = null;
    if (errors != null)
    {
        for (int i = 0; i < errors.Count; ++i)
        {
            var item = errors[i];
            <div class="message-info content-wrapper " style="color:red;border:none;">
                <ul>
                    <li>@Html.Encode(item)</li>
                </ul>

            </div>
        }
    }
    // Html.RenderAction("MpesaDates","SMS");
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    if (listusers != null && listusers.Count > 0)
    {
        <div style="width:100%;margin-left:20px;margin-right:20px;padding-top: 10px;padding-left: 5px;padding-right: 5px;padding-bottom: 10px;border: 1px solid;clear: both;margin: 0 auto;max-width: 1320px;">
            <table id="MyTable" class="display" cellspacing="0" width="100%">
                <thead>
                    <tr>
                        
                        <th>
                            Sender
                        </th>
                        <th>
                            Message
                        </th>

                        <th>
                            Recepient
                        </th>

                        <th>
                            sent time
                        </th>
                    </tr>
                </thead>
                <tbody>
                    @for (int i = 0; i < listusers.Count; ++i)
                    {
                        var item = listusers[i];
                        <tr>
                           
                            <td>@item["sender"]</td>
                            <td>@item["message"]</td>
                            <td>@item["customerphone"]</td>
                            <td>@item["senttime"]</td>
                        </tr>
                    }
                </tbody>
            </table>

            @*<fieldset class="small">
                  <input type="submit" value="Authorise" />
                </fieldset>*@
        @*</div>
    }

    <br></br>
    <br></br>
    <br></br>
    <br></br>
    <br></br>
    <br></br>

}*@